# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Average vectors
#'
#' Efficient implementation of a function to average vectors from a matrix.
#'
#' @param keys [list] containing ids of embeddings in the matrix. Each slot of the [list] is related to a sequence.
#' @param mat embedding [matrix]
#' @examples
#' if (interactive()){
#' # This example should be run with a higher quality model
#' # than the one embedded in fastrtext
#' library(projector)
#' library(fastrtext)
#'
#' model_test_path <- system.file("extdata",
#'                                "model_unsupervised_test.bin",
#'                                package = "fastrtext")
#' model <- load_model(model_test_path)
#' word_embeddings <- get_word_vectors(model,
#'                                     words = head(get_dictionary(model), 2e5))
#'
#' average_vectors(strsplit(x = "this function average vector", split = " "), word_embeddings)
#' }
#' @export
average_vectors <- function(keys, mat) {
    .Call('_projector_average_vectors', PACKAGE = 'projector', keys, mat)
}

