# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add a word prefix
#' 
#' Add a custom prefix to each word of a a line.
#' Number of spaces are normalized.
#'
#' @param texts a [character] containing the original text
#' @param prefix a unit [character] containing the prefix to add (length == 1)
#' @examples
#' add_prefix(c("this is a test", "this is another    test"), "#")
#' @export
add_prefix <- function(texts, prefix) {
    .Call('_projector_add_prefix', PACKAGE = 'projector', texts, prefix)
}

#' @export projector
NULL

