# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add a prefix to each word
#'
#' Add a custom prefix to each word of a a line.
#' Apply it even if the precedent the word is preceded by a punctuation.
#' Code in C++ (efficient).
#'
#' @param texts a [character] containing the original text
#' @param prefix unit [character] containing the prefix to add (length == 1) or [character] with same length than texts
#' @return [character] with prefixed words.
#' @examples
#' add_prefix(c("this is a test", "this is another    test"), "#")
#' @export
add_prefix <- function(texts, prefix) {
    .Call('_projector_add_prefix', PACKAGE = 'projector', texts, prefix)
}

add_pr <- function(line, prefix) {
    .Call('_projector_add_pr', PACKAGE = 'projector', line, prefix)
}

#' @export projector
NULL

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_projector_RcppExport_registerCCallable', PACKAGE = 'projector')
})
